name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  eslint:
    name: Run lint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependency
        run: |
          npm install pnpm -g
          pnpm install

      - name: Run ESLint
        run: pnpm run -w lint
        continue-on-error: true

      - name: commit
        run: |
          git pull
          git config --global user.email akarachen@outlook.com
          git config --global user.name akarachen
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
