name: E2E
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"
            - name: Install dependencies
              run: |
                  pnpm install
            - name: Build component
              run: pnpm build
            - name: Get installed Playwright version
              id: playwright-version
              run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> $GITHUB_ENV
            - name: Caching browsers
              uses: actions/cache
              with:
                path: |
                    ~/.cache/ms-playwright
                key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
            - name: Get Cached browsers
              run: npx playwright install --with-deps
              if: steps.playwright-cache.outputs.cache-hit != 'true'
            - name: Playwright tests
              run: pnpm playwright test

