name: E2E
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"
            - name: Install dependencies
              run: |
                  pnpm install
            - name: Install Playwright Browsers
              run: pnpm dlx playwright install --with-deps
            - name: Build component
              run: pnpm build
            - name: Run Playwright tests
              run: pnpm dlx playwright test
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
