name: Test
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"
            - name: Install dependencies
              run: |
                  pnpm install
            - name: Run vitest
              run: pnpm run test:package
